### ISSUE TITLE
DB schema

### ISSUE THREAD

**Issue by brookeangel** [sarasharif/HeritageHunter#3]
Since rounds are associated with a game which is associated with a user, they don't need to store a user_id - just use a has_one_through to get the user

**Comment by sarasharif** [comment]
/home/sarasharif/Desktop/HeritageHunter/docs/schema.md

I made some other changes too:

Users have many games. Games have 5 guesses. Users have many guesses. Guesses belong to a game and a site. I'm still debating if favorites site_id should reference unesco_sites or guesses
